### ISSUE TITLE
Differences in Finnish and English content

### ISSUE THREAD

**Issue by cxcorp** [HY-TKTL/lapio2016#1]
The exercise `[kotihakemistot]` aka `[home directories]` has different paths in the Finnish version.

https://github.com/HY-TKTL/lapio2016/wiki/Työväline-tehtävät-viikko-1%3A-laitoksen-Ubuntu-ympäristö#kotihakemistot

https://github.com/HY-TKTL/lapio2016/wiki/Computing-Tools-for-CS-studies-exercises-week-1%3A-Department%27s-Ubuntu-environment#home-directories

**Comment by cxcorp** [comment]
Finnish version:

> Käytössäsi on kaksi eri kotihakemistoa.
> - Helsingin yliopiston (AD) kotihakemisto (mikroluokkien tietokoneilla ja laitoksen palvelimilla) polussa `/home/<käyttäjätunnus>`
> - CSFS (CS) kotihakemisto polussa `/cs/home/<käyttäjätunnus>`
> 
> Luo Helsingin yliopiston (AD) kotihakemistoon symbolinen linkki CSFS kotihakemistoon komennolla `ln -s ......... ...`
> 
> Tutustu ln-komennon ohjeeseen komentamalla `man ln` ja selvitä kuinka symbolinen linkki luodaan.

English version:

> You have two different home directories.
> - Helsinki University (AD) home directory (local/paja computers and department's servers)
> - CSFS (CS) home directory is located at `/home/tktl-csfs/fs2/home/usernamehere`
> 
> > Your CSFS home directory might also be located at `/home/tktl-csfs/fs/home/usernamehere`
> 
> Make a symbolic link in your AD home directory which points to your CSFS home directory. `ln -s ........ .......`
> 
> Check out ln command manual by typing `man ln` ja find out how to create a symbolic link.

Also notice how the English version says: "_...by typing `man ln` **ja** find out how to..._"

**Comment by emillaine** [comment]
Thanks for reporting! It's fixed now.
