### ISSUE TITLE
Week 3 - [rsync-directory] typo

### ISSUE THREAD

**Issue by ivanicspeter92** [HY-TKTL/lapio2016#2]
In the first sentence I found the following typo: 

> Use rsync to copy a directory (e.g. ~/Documents) from your local computer to the directory **~/bakup** on **departments** server. 

Shouldn't it be "~/backup" and "department's" by any chance? Same for the folder name in the paragraphs and sentences to follow.

**Comment by Coolnesss** [comment]
Hey,

That was probably intentional (some kind of a joke) but i fixed it anyways :)

Thanks for reporting!

**Comment by ivanicspeter92** [comment]
Ah okay haha :D Thanks!
